apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: h2os.h2o.ai
spec:
  group: h2o.ai
  names:
    kind: H2O
    plural: h2os
    singular: h2o
  scope: Namespaced
  version: v1beta
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            nodes:
              type: integer
            version:
              type: string
            customImage:
              type: object
              properties:
                image:
                  type: string
                command:
                  type: string
              required: [ "image" ]
            resources:
              type: object
              properties:
                cpu:
                  type: integer
                  minimum: 1
                memory:
                  type: string
                  pattern: "^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$"
                memoryPercentage:
                  type: integer
                  minimum: 1
                  maximum: 100
              required: [ "cpu", "memory" ]
          oneOf:
            - required: [ "version" ]
            - required: [ "customImage" ]
          required: [ "nodes", "resources" ]
        status:
          type: object
status:
  acceptedNames:
    kind: ''
    plural: ''
  conditions: null
  storedVersions: null