name: Release pipeline

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    
    runs-on: ubuntu-latest
    env:
      TARGET: x86_64-unknown-linux-musl
    
    steps:
      - name: actions-k3s
        uses: debianmaster/actions-k3s@v1.0.0
        id: k3s
      - uses: actions/checkout@v2
      - name: Install target
        run: rustup target add $TARGET
      - name: Install dependencies
        run: sudo apt install musl musl-tools -y
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Release build
        run: cargo build --release --target $TARGET
