name: Operator Release
# Creates a release for push event  to matching operator-*, i.e. v1.0, v20.15.10
# The release created is a draft - this means it has to be checked and published manually afterwards to enforce manual check.
on:
  workflow_dispatch:
    inputs:
      new_version:
        description: 'New version'
        required: true

env:
  CARGO_TERM_COLOR: always
  TARGET_LINUX: x86_64-unknown-linux-gnu
  RELEASED_ARTIFACT_NAME: h2o-operator
  OPERATOR_NAME: h2o-operator

jobs:

  build-linux:
    name: Tests & Linux binary
    runs-on: ubuntu-latest
    steps:
      - name: Install cross-platform compile dependencies
        run: sudo apt install pkg-config libssl-dev -y
      - name: Start K3S
        uses: debianmaster/actions-k3s@v1.0.1
        id: k3s
        with:
          version: 'latest'
      - uses: actions/checkout@v2
      - name: Extract current version
        id: current-ver
        run: |
          VERSION=$(cat operator/Cargo.toml | sed -n "s/^version\s*=\s*\"\([0-9]*\.[0-9]*\.[0-9]*\)\"$/\1/p")
          echo "::set-output name=version::$VERSION"
      - name: Cargo test
        run: |
          # 🄿🅁🄴🄿🄰🅁🄰🅃🄸🄾🄽🅂
          # debianmaster/actions-k3s sets owner of the Kubeconfig output to a different user.
          # To generate kubeconfigs for specific service accounts, current user must have read rights to the cluster-admin kubeconfig folder
          sudo chown $(id -u):$(id -g) /tmp/output/

          # Create cluster role and a service account with permissions and related kubeconfig for DEPLOYMENT MODULE
          kubectl apply -f deployment/tests/permissions/cluster_role.yaml
          bash tests_common/k8s_cluster_setup/kubeconfig.sh h2o-deployment default

          # Create cluster role and a service with permissions  and related kubeconfig for OPERATOR
          kubectl apply -f operator/tests/permissions/cluster_role.yaml
          kubectl apply -f operator/bundle/manifests/h2os.h2o.ai.crd.yaml
          bash tests_common/k8s_cluster_setup/kubeconfig.sh h2o-operator default

          # 🅃🄴🅂🅃🅂
          # Each module is tested with kubeconfig reflecting service account with just enough permissions
          # for the given module.

          # Test DEPLOYMENT module
          export KUBECONFIG=$(pwd)/kubeconfigs-generated/kubeconfig-h2o-deployment-default.yaml
          cd deployment
          cargo test --verbose
          cd ../

          # Test OPERATOR module
          export KUBECONFIG=$(pwd)/kubeconfigs-generated/kubeconfig-h2o-operator-default.yaml
          cd operator
          cargo test --verbose
          cd ../
      - name: Release build
        run: rustup target add ${{ env.TARGET_LINUX }} && cargo build -p ${{ env.RELEASED_ARTIFACT_NAME }} --release --target ${{ env.TARGET_LINUX }}
      - name: Create ${{ env.TARGET_LINUX }} ZIP package
        run: zip -j ${{ env.RELEASED_ARTIFACT_NAME }}_${{ env.TARGET_LINUX }}.zip target/${{ env.TARGET_LINUX }}/release/${{ env.RELEASED_ARTIFACT_NAME }} LICENSE
      - name: Upload ${{ env.TARGET_LINUX }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.TARGET_LINUX }}
          path: ${{ env.RELEASED_ARTIFACT_NAME }}_${{ env.TARGET_LINUX }}.zip

  build-docker:
    needs: [build-linux]
    name: Build Operator Dockerfile
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Extract current version
        id: current-ver
        run: |
          VERSION=$(cat operator/Cargo.toml | sed -n "s/^version\s*=\s*\"\([0-9]*\.[0-9]*\.[0-9]*\)\"$/\1/p")
          echo "::set-output name=version::$VERSION"
      - name: Build Operator Dockerfile
        run: |
          pip install requests argparse
          echo "${{ secrets.OPERATOR_RED_HAT_REGISTRY_KEY }}" | docker login -u unused scan.connect.redhat.com --password-stdin
          docker build -t ${{ secrets.OPERATOR_RED_HAT_SCAN_TAG_PREFIX }}${{ env.OPERATOR_NAME }}:${{steps.current-ver.outputs.version}} -f operator/docker/Dockerfile-operator . --build-arg OPERATOR_VERSION=${{ steps.current-ver.outputs.version }} --no-cache
          OPERATOR_DIGEST=$(docker push ${{ secrets.OPERATOR_RED_HAT_SCAN_TAG_PREFIX }}${{ env.OPERATOR_NAME }}:${{ steps.current-ver.outputs.version }} | sed -n 's/.*\(sha256:[a-zA-Z0-9]*\).*$/\1/p')
          echo $OPERATOR_DIGEST
          python operator/release/red_hat_docker_certification.py --api_key ${{ secrets.RED_HAT_CONNECT_API_KEY }} --pid ${{ secrets.OPERATOR_RED_HAT_PID }} --tag ${{ steps.current-ver.outputs.version }} $OPERATOR_DIGEST
          docker logout
          echo "${{ secrets.OPERATOR_BUNDLE_RED_HAT_REGISTRY_KEY }}" | docker login -u unused scan.connect.redhat.com --password-stdin
          CREATED_DATE=$(date --utc +%FT%T%Z)
          sed -i "s/<created-date>/$CREATED_DATE/g" operator/bundle/manifests/h2o-operator.clusterserviceversion.yaml
          sed -i "s/<version>/${{ steps.current-ver.outputs.version }}/g" operator/bundle/manifests/h2o-operator.clusterserviceversion.yaml
          cat operator/bundle/manifests/h2o-operator.clusterserviceversion.yaml
          docker build -t ${{ secrets.OPERATOR_BUNDLE_RED_HAT_SCAN_TAG_PREFIX }}${{ env.OPERATOR_NAME }}-bundle:${{steps.current-ver.outputs.version}} -f operator/docker/Dockerfile-operator-bundle . --no-cache
          BUNDLE_DIGEST=$(docker push ${{ secrets.OPERATOR_BUNDLE_RED_HAT_SCAN_TAG_PREFIX }}${{ env.OPERATOR_NAME }}-bundle:${{ steps.current-ver.outputs.version }} | sed -n 's/.*\(sha256:[a-zA-Z0-9]*\).*$/\1/p')
          echo $BUNDLE_DIGEST
          python operator/release/red_hat_docker_certification.py --api_key ${{ secrets.RED_HAT_CONNECT_API_KEY }} --pid ${{ secrets.OPERATOR_BUNDLE_RED_HAT_PID }} --tag ${{ steps.current-ver.outputs.version }} $BUNDLE_DIGEST
          docker logout

  gh-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [ build-docker ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract current version
        id: current-ver
        run: |
          VERSION=$(cat operator/Cargo.toml | sed -n "s/^version\s*=\s*\"\([0-9]*\.[0-9]*\.[0-9]*\)\"$/\1/p")
          echo "::set-output name=version::$VERSION"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: operator-${{ steps.current-ver.outputs.version }}
          release_name: H2O K8S Operator v${{ steps.current-ver.outputs.version }}
          draft: false
          prerelease: false
      - name: Download ${{ env.TARGET_LINUX }} binary
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.TARGET_LINUX }}
      - name: Upload ${{ env.TARGET_LINUX }} asset
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.RELEASED_ARTIFACT_NAME }}_${{ env.TARGET_LINUX }}.zip
          asset_name: ${{ env.TARGET_LINUX }}
          asset_content_type: application

  push-new-version-git:
    needs: [gh-release]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump up operator version
        run: sed -i "s/version\s=\s\"\(0.1.0\)\"/version = \"${{ github.event.inputs.new_version }}\"/g" operator/Cargo.toml
      - name: Commit new version
        uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: 'Operator Release'
          author_email: '<pavel.pscheidl@h2o.ai>'
          message: 'Version ${{ github.event.inputs.new_version }}'
          add: 'operator/Cargo.toml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}