name: Rust

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: actions-k3s
        uses: debianmaster/actions-k3s@v1.0.0
        id: k3s
      - uses: actions/checkout@v2
      - env:
          TARGET: x86_64-unknown-linux-musl
      - name: Install target
        run: rustup target add $TARGET
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Release build
        run: cargo build --release --target $TARGET
